# Generated by Django 4.0.2 on 2022-02-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('gst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdue',
            name='generatedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='clienttaxdues', to='users.taxaccountant', verbose_name='taxaccountants'),
        ),
        migrations.AddField(
            model_name='taxdue',
            name='taxpayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='taxdues', to='users.taxpayer', verbose_name='taxpayers'),
        ),
        migrations.AddField(
            model_name='taxdetails',
            name='taxdue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='taxdetails', to='gst.taxdue', verbose_name='taxdues'),
        ),
        migrations.AddField(
            model_name='taxdetails',
            name='taxpayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='taxdetails', to='users.taxpayer', verbose_name='taxpayers'),
        ),
        migrations.AddField(
            model_name='service',
            name='taxpayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='services', to='users.taxpayer', verbose_name='taxpayers'),
        ),
        migrations.AddField(
            model_name='product',
            name='taxpayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='products', to='users.taxpayer', verbose_name='taxpayers'),
        ),
    ]
